homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('edu/', views.edu, name='edu'),
    path('skills/', views.skills, name='skills'),
    path('exp/', views.exp, name='exp'),
    path('contact/', views.contact, name='contact'),
    path('about/swot/', views.swot, name='swot'),
]

story04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def about(request):
    return render(request, 'About.html')

def edu(request):
    return render(request, 'Education.html')

def skills(request):
    return render(request, 'Skills.html')

def exp(request):
    return render(request, 'Experiences.html')

def contact(request):
    return render(request, 'Contact.html')

def swot(request):
    return render(request, 'Swot.html')

homepage/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | About Me</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/about_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  
        

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">About</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Education_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:edu' %}"><div class="text">Edu</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
                
            </div>
        </div>

        <div class="container-fluid left-right-most">
            <div class="header top right">
                <!-- fill the header with dropdown -->
                <div class="dropdown ">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                      Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'homepage:homepage' %}">Home</a>
                        <a class="dropdown-item disabled" href="#">About Me</a>
                        <a class="dropdown-item" href="{% url 'homepage:edu' %}">Edu</a>
                        <a class="dropdown-item" href="{% url 'homepage:skills' %}">Skills</a>
                        <a class="dropdown-item" href="{% url 'homepage:exp' %}">Exp</a>
                        <a class="dropdown-item" href="{% url 'homepage:contact' %}">Contact</a>
                    </div>
                </div>
            </div>
            
            <div id="about">
                <div class="d-flex flex-column margin-left">
                    <h1 class="title">About Me</h1>
                    <div class="row">
                        <div class="col-md-4 left-right-most center">
                            <picture>
                                <source class="landscape_photo" media="(max-width: 767px)" srcset="{% static 'images/Photo-landscape-crop.jpg' %}" />
                                <img class=".mx-auto .d-block profile" src="{% static 'images/Photo.jpg' %}" alt="main photo" />
                            </picture>
                        </div>
                        <div class="col-md-7 left-right-most">
                            <p class="leftmost">
                                I’m a highly <strong>motivated</strong> and <strong>hardworking</strong> person. Excellent in <strong>team working</strong>  
                                and always try to be a <strong>professional</strong> at any possible time. I give someone chances to criticize my performance 
                                for the better. <br><br>
                                From a high school, my passion is <strong>technology</strong>. That's why I started learning in 
                                a computer science major. I really hope someday I could make something <strong>helpful</strong> with my knowledge 
                                and spread education about how technology can change our world.
                            </p>
                            <a href="{% url 'homepage:swot' %}" target="_blank"><img class="swot_icon" src="{% static 'images/Icon/SWOT_icon.png' %}" alt="swot icon" /></a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

homepage/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Contact</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/contact_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Education_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:edu' %}"><div class="text">Edu</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Contact</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid left-right-most">
            <div class="header right">
                <!-- fill the header with dropdown -->
                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                        Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'homepage:homepage' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'homepage:about' %}">About Me</a>
                        <a class="dropdown-item" href="{% url 'homepage:edu' %}">Edu</a>
                        <a class="dropdown-item" href="{% url 'homepage:skills' %}">Skills</a>
                        <a class="dropdown-item" href="{% url 'homepage:exp' %}">Exp</a>
                        <a class="dropdown-item disabled" href="#">Contact</a>
                    </div>
                </div>
            </div>

            <div id="contact">
                <div class="d-flex flex-column margin-left center-icon">
                    <h1 class="title">Contact</h1>
                    <p>If you have any questions, don’t hesitate to ask me on</p>
                    <div class=".d-flex flex-row center-icon">
                        <a class="btn btn-link" href="mailto:jilham.luthfi15@gmail.com" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Email.png' %}" alt="email icon" class="iconContact"/>
                        </a>
                        <a class="btn btn-link" href="https://www.linkedin.com/in/jilham-luthfi-78713417b/" target="_blank" role="button">
                            <img src="{% static 'images/Icon/LinkedIn.png' %}" alt="email icon" class="iconContact"/>
                        </a>
                        <a class="btn btn-link" href="#" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Instagram.png' %}" alt="email icon" class="iconContact" />
                        </a>
                        <a class="btn btn-link" href="https://twitter.com/Mjilham_luthfi" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Twitter.png' %}" alt="email icon" class="iconContact" />
                        </a>
    
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

homepage/templates/Education.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Education</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/education_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Education_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Edu</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid left-right-most">
            <div class="header top right">
                <!-- fill the header with dropdown -->
                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                        Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'homepage:homepage' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'homepage:about' %}">About Me</a>
                        <a class="dropdown-item disabled" href="#">Edu</a>
                        <a class="dropdown-item" href="{% url 'homepage:skills' %}">Skills</a>
                        <a class="dropdown-item" href="{% url 'homepage:exp' %}">Exp</a>
                        <a class="dropdown-item" href="{% url 'homepage:contact' %}">Contact</a>
                    </div>
                </div>
            </div>

            <div id="edu">
                <div class="d-flex flex-column margin-left">
                    <h1 class="title">Education</h1>
                    <div class="row">
                        <div class="col-md-7 left-right-most center-icon">
                            <h2>Universitas Indonesia</h2>
                            <h3>Computer Science Major</h3>
                            <p>
                                I am an undergraduate student of Computer Science major at Universitas Indonesia. 
                                Computer Science of Universitas Indonesia (CSUI) is one of the foremost institutions 
                                in Indonesia which offers degree programs in computer science and information 
                                technology. CSUI has played a key role in developing indormation technology in Indonesia, 
                                and continually delivers high-quality education, reserach, and services to meet 
                                the needs of its stakeholders. 
                            </p>
                        </div>
                        <div class="col-md-5 left-right-most">
                            <img class="makara" src="{% static 'images/Icon/Makara_UI.png' %}" alt="Makara UI" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

                
    </body>
</html>

homepage/templates/Experiences.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Experiences</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/experiences_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Education_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:edu' %}"><div class="text">Edu</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Exp</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="container-fluid left-right-most">
            <div class="header right">
                <!-- fill the header with dropdown -->
                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                        Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'homepage:homepage' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'homepage:about' %}">About Me</a>
                        <a class="dropdown-item" href="{% url 'homepage:edu' %}">Edu</a>
                        <a class="dropdown-item" href="{% url 'homepage:skills' %}">Skills</a>
                        <a class="dropdown-item disabled" href="#">Exp</a>
                        <a class="dropdown-item" href="{% url 'homepage:contact' %}">Contact</a>
                    </div>
                </div>
            </div>

            <div id="exp" class="left-right-most">
                <div class="d-flex flex-column margin-left">
                    <h1 class="title">Experiences</h1>
                    <div class="d-flex flex-row small-size">
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/PythonLogo.png' %}" alt="python logo" />
                            <h2>DDP0</h2>
                            <p>Mentor<br>July, 2019 - Aug, 2019</p>
                        </div>
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/CGTLogo.png' %}" alt="CGT logo" />
                            <h2>Computers Get Together</h2>
                            <p>Staff of Decoration<br>Feb, 2019 - April, 2019</p>
                        </div>
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/BEM Fasilkom UI Logo.png' %}" alt="BEM Fasilkom UI logo" />
                            <h2>BEM Fasilkom UI</h2>
                            <p>Staff of Student Advocacy and Welfare<br>Feb, 2019 - present</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

homepage/templates/Skills.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Skills</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/skills_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Education_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:edu' %}"><div class="text">Edu</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Skills</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'homepage:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="header top right">
            <!-- fill the header with dropdown -->
            <div class="dropdown">
                <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                    Menu
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'homepage:homepage' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'homepage:about' %}">About Me</a>
                    <a class="dropdown-item" href="{% url 'homepage:edu' %}">Edu</a>
                    <a class="dropdown-item disabled" href="#">Skills</a>
                    <a class="dropdown-item" href="{% url 'homepage:exp' %}">Exp</a>
                    <a class="dropdown-item" href="{% url 'homepage:contact' %}">Contact</a>
                </div>
            </div>
        </div>

        <div class="container-fluid left-right-most">
                <div id="skills">
                    <div class="d-flex flex-column margin-left">
                        <h1 class="title">Skills</h1>
                        <div class="row">
                            <h2>Programming Skills</h2>
                            <div class="col-md-3 left-right-most">
                                <p>Python</p>
                            </div>
                            <div class="col-md-3 left-right-most">
                                <p>Java</p>
                            </div>
                            <div class="col-md-3 left-right-most">
                                <p>HTML</p>
                            </div>
                            <div class="col-md-3 left-right-mostcol-border">
                                <p>CSS</p>
                            </div>
                        </div>
                        <div class="row">
                            <h2>Non-Programming Skills</h2>
                            <div class="col-md-4 left-right-most">
                                <p>Adobe Illustrator</p>
                            </div>
                            <div class="col-md-4 left-right-most">
                                <p>Ms. Powerpoint</p>
                            </div>
                            <div class="col-md-4 left-right-most">
                                <p>Creative Arts</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
</html>